SELECT DISTINCT(D.ID), D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE
WHERE S.NAME IN ('Python', 'C#')
ORDER BY 1

/* POINT
JOIN ON D.SKILL_CODE & S.CODE 이렇게 & (BINARY AND) 연산 가능. 
DISTINCT (ID) 해야 함.
*/