SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS d
WHERE (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') = (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'))
OR (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') = (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'))
ORDER BY 1;