SELECT 
    DISTINCT(R.CAR_ID)
FROM 
    CAR_RENTAL_COMPANY_CAR R, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE 
    R.CAR_ID = H.CAR_ID
    AND
    R.CAR_TYPE = '세단'
    AND
    MONTH(H.START_DATE) = 10
ORDER BY 1 DESC;