-- 코드를 작성해주세요
SELECT ROUND(AVG(
    CASE
        WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH
        END),2) AS AVERAGE_LENGTH
FROM FISH_INFO


/*
1. IFNULL 활용 풀이
SELECT ROUND(AVG(IFNULL(LENGTH,10)),2) AS AVERAGE_LENGTH
FROM FISH_INFO;

2. 서브쿼리 활용 풀이
SELECT ROUND(AVG(a.LENGTH),2) AS AVERAGE_LENGTH
FROM (
    SELECT ID, FISH_TYPE,
        CASE
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
            END AS LENGTH
    FROM FISH_INFO) a

    */