WITH SUB AS ( 
    SELECT 
        CAR_ID
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE >= DATE_FORMAT('2022-08-01','%Y-%m-%d')
        AND
        START_DATE <= DATE_FORMAT('2022-10-31','%Y-%m-%d')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
    ORDER BY CAR_ID
)

SELECT 
    MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY A, SUB S
WHERE 
    A.CAR_ID = S.CAR_ID
    AND
    A.START_DATE >= DATE_FORMAT('2022-08-01','%Y-%m-%d')
    AND
    A.START_DATE <= DATE_FORMAT('2022-10-31','%Y-%m-%d')
GROUP BY 1, 2
ORDER BY 1, 2 DESC;