SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (SUB.M - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA E
    LEFT JOIN
    (SELECT YEAR(DIFFERENTIATION_DATE) AS Y , MAX(SIZE_OF_COLONY) AS M
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) AS SUB
    ON YEAR(E.DIFFERENTIATION_DATE) = SUB.Y
    
ORDER BY 1 ASC, 2 ASC ;