SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE
    NOT SUBSTRING(CONV(GENOTYPE, 10, 2), -2, 1) = 1 
    AND (SUBSTRING(CONV(GENOTYPE, 10, 2), -1, 1) = 1
        OR
         SUBSTRING(CONV(GENOTYPE, 10, 2), -3, 1) = 1)
;