WITH BOOKSALE AS (
    SELECT B.CATEGORY, S.SALES, S.SALES_DATE
    FROM BOOK B, BOOK_SALES S
    WHERE B.BOOK_ID = S.BOOK_ID
)

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOKSALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY;